### ISSUE TITLE
Version 0.6

### ISSUE THREAD

**Issue by gavinballard** [discolabs/disco_app#10]
A task to keep track of the feature list for v0.6 of `DiscoApp`.
- [x] New Plans and Charges framework (#5)
- [x] Update OAuth flow to support "state" parameters (#6)
- [x] Optional Email support generator (#7)
- [x] Update default Bootstrap styling to be more "Shopify" (#9)
- [x] Update documentation (#11)
